name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore AspireTodoApp.Tests/AspireTodoApp.Tests.csproj

    - name: Build
      run: dotnet build AspireTodoApp.Tests/AspireTodoApp.Tests.csproj --no-restore

    - name: Test
      run: dotnet test AspireTodoApp.Tests/AspireTodoApp.Tests.csproj --no-build --verbosity normal
